disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_unwrapping
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message

line_length:
  warning: 120
  error: 200

excluded:
  - Carthage
  - Pods
  - fastlane
  - build 